-- USE db_product;


SET IDENTITY_INSERT categories ON;
INSERT INTO categories (id, name, url_key) VALUES (1,'Hombre /Ropa /Casacas y Chalecos', 'hombre-ropa-casacas-y-chalecos');
INSERT INTO categories (id, name, url_key) VALUES (2,'Hombre /Ropa /Chompas', 'hombre-ropa-chompas');
INSERT INTO categories (id, name, url_key) VALUES (3,'Hombre /Ropa /Poleras y Sweatshirts', 'hombre-ropa-poleras-y-sweatshirts');
INSERT INTO categories (id, name, url_key) VALUES (4,'Hombre /Ropa /Pantalones', 'hombre-ropa-pantalones');
INSERT INTO categories (id, name, url_key) VALUES (5,'Hombre /Ropa /Jeans', 'hombre-ropa-jeans');
INSERT INTO categories (id, name, url_key) VALUES (6,'Hombre /Calzado /Zapatos', 'hombre-calzado-zapatos');
INSERT INTO categories (id, name, url_key) VALUES (7,'Hombre /Accesorios /Corbatas', 'hombre-accesorios-corbatas');
INSERT INTO categories (id, name, url_key) VALUES (8,'Hombre /Jeans /Polos', 'hombre-jeans-polos');
INSERT INTO categories (id, name, url_key) VALUES (9,'Hombre /Jeans /Poleras y Chompas', 'hombre-jeans-poleras-y-chompas');
INSERT INTO categories (id, name, url_key) VALUES (10,'Mujer /Ropa /Polos', 'mujer-ropa-polos');
INSERT INTO categories (id, name, url_key) VALUES (11,'Mujer /Ropa /Vestidos', 'mujer-ropa-vestidos');
INSERT INTO categories (id, name, url_key) VALUES (12,'Mujer /Ropa /Chompas', 'mujer-ropa-chompas');
INSERT INTO categories (id, name, url_key) VALUES (13,'Mujer /Ropa /Casacas y Sacos', 'mujer-ropa-casacas-y-sacos');
INSERT INTO categories (id, name, url_key) VALUES (14,'Mujer /Ropa /Jeans', 'mujer-ropa-jeans');
INSERT INTO categories (id, name, url_key) VALUES (15,'Mujer /Ropa /Pantalones', 'mujer-ropa-pantalones');
INSERT INTO categories (id, name, url_key) VALUES (16,'Mujer /Ropa /Faldas', 'mujer-ropa-faldas');
INSERT INTO categories (id, name, url_key) VALUES (17,'Mujer /Ropa /Lenceria y Ropa Interior', 'mujer-ropa-lenceria-y-ropa-interior');
INSERT INTO categories (id, name, url_key) VALUES (18,'Mujer /Calzado /Botas y Botines', 'mujer-calzado-botas-y-botines');
INSERT INTO categories (id, name, url_key) VALUES (19,'Mujer /Jeans /Poleras y Sweatshirts', 'mujer-jeans-poleras-y-sweatshirts');
INSERT INTO categories (id, name, url_key) VALUES (20,'Mujer /Jeans /Casacas y Chompas', 'mujer-jeans-casacas-y-chompas');
INSERT INTO categories (id, name, url_key) VALUES (21,'Mujer /Jeans /Jeans', 'mujer-jeans-jeans');
INSERT INTO categories (id, name, url_key) VALUES (22,'Mujer /Jeans /Pantalones, Faldas y Shorts', 'mujer-jeans-pantalones-faldas-y-shorts');
INSERT INTO categories (id, name, url_key) VALUES (23,'Niños /Polos', 'ninos-polos');
INSERT INTO categories (id, name, url_key) VALUES (24,'Niños /Casacas y Abrigos', 'ninos-casacas-y-abrigos');
INSERT INTO categories (id, name, url_key) VALUES (25,'Niñas /Polos y Blusas', 'ninas-polos-y-blusas');
INSERT INTO categories (id, name, url_key) VALUES (26,'Niñas /Vestidos y Faldas', 'ninas-vestidos-y-faldas');
INSERT INTO categories (id, name, url_key) VALUES (27,'Niñas /Chompas y Cardigans', 'ninas-chompas-y-cardigans');
INSERT INTO categories (id, name, url_key) VALUES (28,'Niñas /Pantalones y Shorts', 'ninas-pantalones-y-shorts');
INSERT INTO categories (id, name, url_key) VALUES (29,'Mujer /Ropa /T-Shirts', 'mujer-ropa-t-shirts');
SET IDENTITY_INSERT categories OFF;


INSERT INTO products (name, description, price, category_id) VALUES ('PRINTED NOVA LEATHER DR','Estos elegantes mocasines driver están confeccionados en piel y se realzan con una tira textil que luce el logo de Nova',749.9,6);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA SLIM SOFT TENCEL SCOOP-NK TOP','Esta favorecedora camiseta de corte slim con cuello redondo y amplio está confeccionada en suave tencel elástico',219.9,29);
INSERT INTO products (name, description, price, category_id) VALUES ('CORBATA GINGHAM CHECK','Esta favorecedora camiseta de corte slim con cuello redondo y amplio está confeccionada en suave tencel elástico',219.9,29);
INSERT INTO products (name, description, price, category_id) VALUES ('BRASIER UNLINED BRALETTE','Esta corbata de pura seda con un llamativo diseño de cuadros es el complemento ideal para llevar con camisas de diferentes colores',229.9,7);
INSERT INTO products (name, description, price, category_id) VALUES ('POLO PIJAMA SHORT SLEEVE TEE','Este bralette de espalda deportiva, suave, cómodo y flexible, es perfecto para estar en casa o para salir a hacer recados',199.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('BRASIER MICRO PUSH UP BRA','Actualiza tus prendas de estilo informal con esta camiseta de corte amplio, confeccionada en puro algodón para disfrutar de tus días de relax con la máxima comodidad',199.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('BRASIER PSHUP BRA W /STPY BK','Sujetador push-up de poliamida y elastano, acabado de tacto suave e interior aterciopelado',219.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS TH HARDWARE LEATHER DRIVER','Sujetador push-up de poliamida y elastano, acabado de tacto suave e interior aterciopelado',219.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN WIDE LEG HW SUKI','Sujetador push-up de poliamida y elastano, acabado de tacto suave e interior aterciopelado',219.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('CALZON BIKINI PRINT','Sujetador push-up de poliamida y elastano, acabado de tacto suave e interior aterciopelado',219.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('BRASIER DB PSHUP BRA STRAP & BND LUMIN','Este zapatos de cuero, son la combinación perfecta de zapatillas deportivas y calzado formal',699.9,6);
INSERT INTO products (name, description, price, category_id) VALUES ('BRASIER DB PSHUP BRA STRAP & BND BRIGH','Estos Jeans presentan una moderna silueta con pernera ancha que se completa con detalles informales como el acabado con efecto desteñido y los bajos sin rematar',649.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTAS TW SHANO','',119.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTAS TWSHYENNE','',219.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA M LW VARSITY BOMBER','',219.9,17);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA TJM ESSENTIAL PADDED JACKET','',799.9,18);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA PACKABLE RECYCLED BOMBER','',799.9,18);
INSERT INTO products (name, description, price, category_id) VALUES ('CHALECO TJM MIX MEDIA SHERPA VEST','',799.9,18);
INSERT INTO products (name, description, price, category_id) VALUES ('SWEATSHIRT TJM RLX NY GRUNGE CB HOODIE','Opta por esta cazadora bomber acolchada cuando las temperaturas empiecen a bajar',1090.9,1);
INSERT INTO products (name, description, price, category_id) VALUES ('SWEATSHIRT NOVA LOGO TIPPED HOODY','Esta chaqueta acolchada y cálida de diseño sencillo, presenta un diseño con cierre de cremallera y cuello alto con el logo clásico de Nova Jeans en el pecho',729.9,9);
INSERT INTO products (name, description, price, category_id) VALUES ('SWEATSHIRT MONOTYPE EMBRO BRUSHED ZIP THR','Esta cazadora bomber plegable está confeccionada en poliéster reciclado y presenta un cálido diseño acolchado',1190.9,1);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN STRAIGHT DENTON STR ARBOR BLAC','Este chaleco de peluche acolchado, confeccionado en una cálida mezcla de poliéster reciclado, está completamente forrado y presenta un cierre de cremallera',669.9,9);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN STRAIGHT DENTON STR ELGIN GREY','Esta sudadera con capucha, confeccionada en puro algodón, se presenta con un corte amplio y un diseño de doble capa en colores a contraste',659.9,9);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALON BLEECKER FAKE SOLID WOOL LOOK','Esta sudadera con capucha en mezcla de algodón orgánico cuenta con puños ribeteados, que añaden un toque de color distintivo a tus looks informales',699.9,3);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALON IM DENTON CTN SATIN PD','Aporta un toque moderno a tus looks con este cálido jersey, que presenta un cierre de cremallera y está confeccionado en mezcla de algodón con un suave acabado peinado',849.9,3);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA TJM L /S CLSC CIRCLE ENTRY TEE','Este jean presenta un corte recto clásico y entallado con un sutil efecto desteñido que logra un look desgastado ideal',699.9,5);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN FEMININE SEASONAL RAINBOOT','Este jean está confeccionado en un tejido con Flex Technology para que disfrutes de una comodidad absoluta en tus actividades del fin de semana',699.9,5);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA TJW MODERN PUFFER','Este pantalón de corte ajustado está confeccionado en tejido de mezcla de algodón elástico peinado y es ideal para crear looks semiformales',779.9,4);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA TJW SHERPA JACKET','Este pantalón de corte ajustado está confeccionado en tejido de mezcla de algodón elástico peinado y es ideal para crear looks semiformales',779.9,4);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA REG SPLIT GLOBAL STRIPE ZIP UP','Esta temporada disfruta de tus viajes al máximo con este pantalón exclusivo de Nova, confeccionado de algodón y elástico para garantizar la mayor comodidad posible las veinticuatro horas del día',779.9,4);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA NYLON VARSITY JACKET','Esta sencilla camiseta de corte clásico, confeccionada en cómodo punto de puro algodón aterciopelado, luce vistosos detalles distintivos que le dan un toque divertido al diseño',219.9,8);
INSERT INTO products (name, description, price, category_id) VALUES ('CHALECO TJW ALASKA PUFFER VEST','Estos botines, perfectos para el mal tiempo, repelen el agua e incorporan una suela dentada gruesa, que resulta práctica a la vez que moderna',699.9,18);
INSERT INTO products (name, description, price, category_id) VALUES ('CHALECO TJW DIAMOND QUILT VEST','Estos botines, perfectos para el mal tiempo, repelen el agua e incorporan una suela dentada gruesa, que resulta práctica a la vez que moderna',699.9,18);
INSERT INTO products (name, description, price, category_id) VALUES ('FALDA FLUID TWILL PLEATED MIDI SKIR','Esta chaqueta acolchada es sumamente cálido y duradero, este cuenta con un relleno suave hecho a base de nailon reciclado y se destaca por llevar unos sutiles detalles de Nova Jeans',859.9,20);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN MOM JEAN UHR TPR DG6035','Esta chaqueta de peluche, con un interior acolchado ideal para los días fríos, tiene un marcado estilo noventero',859.9,20);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN TH FLEX HARLEM U SKINNY HW LUZ','Esta chaqueta de viscosa elástica presenta un llamativo cuello de punto elástico con los colores distintivos de la marca',779.9,13);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN RELAXED STRAIGHT HW SAU','Inspirada en el clásico modelo bomber, esta cálida chaqueta universitaria de diseño acolchado está confeccionada en un material reciclado y presenta un cuello italiano ancho',1050.9,13);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN BALLOON HW A SAU','La chaqueta Alaska acolchada, confeccionada en materiales reciclados que respetan el medioambiente, presenta un diseño actual inspirado en el archivo de Nova y te protege de los elementos extremos',899.9,19);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN BALLOON HW A AGED CLR','Este chaleco con diseño acolchado a rombos combina estilo deportivo y elegante a la perfección',729.9,19);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALÓN SLIM COTTON GABARDINE PANT','Este chaleco con diseño acolchado a rombos combina estilo deportivo y elegante a la perfección',729.9,19);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALÓN MD CORE SLIM STRAIGHT PANT','Si quieres estar a la moda, Nova te trae las últimas tendencias, esta falda midi plisada le brinda un toque elegante a tus looks de fin de semana y puedes combinarla facilmente con camisas o blusas de corte cropped',659.9,16);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALÓN SLIM STRAIGHT TRAVEL PANT','Si quieres estar a la moda, Nova te trae las últimas tendencias, esta falda midi plisada le brinda un toque elegante a tus looks de fin de semana y puedes combinarla facilmente con camisas o blusas de corte cropped',659.9,16);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALÓN MD CORE RELAXED STRAIGHT PANT','Estos modernos jeans confeccionados en mezcla de algodón lucen un vistoso estampado sobre banderas y detalles de Nova Jeans, además cuentan con un ajuste mom que brinda mayor comodidad para las damas',659.9,21);
INSERT INTO products (name, description, price, category_id) VALUES ('SWEATER SMD TONAL TEXTURE C-NK SWEATER','Estos favorecedores Jeans superceñidos están confeccionados en un cómodo tejido denim con Flex Technology y se realzan con un efecto desteñido integral',659.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('VESTIDO TJW CABLE FLAG HOODIE DRESS','Estos Jeans de corte amplio y pernera recta presentan un favorecedor talle alto y se realzan con un efecto desteñido en los muslos',699.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('VESTIDO POLKADOT SHORT V-NECK DRESS LS','Este jeans es una opción cómoda y perfecta para el uso diario, esta prenda confeccionada en mezcla de algodón es una opción versátil que brinda una comodidad excepcional',699.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('VESTIDO SOFT WOOL POLO DRESS','Estos Jeans blancos, inspirados en la estética de los años 80, presentan un corte globo, un talle alto clásico y perneras amplias',659.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('VESTIDO FEATHER PRINT VIS CREPE DRESS','Estos Jeans blancos, inspirados en la estética de los años 80, presentan un corte globo, un talle alto clásico y perneras amplias',659.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA ESSENTIAL DOWN FUR HOOD JACKET NIÑA','Este pantalón de estilo elegante presenta un favorecedor corte slim y está confeccionado en gabardina de algodón elástico para mayor facilidad de movimiento',659.9,15);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA NEW YORK PUFFER JACKET NIÑA','Este pantalón clásico de pernera recta está confeccionado en mezcla de viscosa elástica con un elegante corte slim',689.9,15);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA NEW YORK TARTAN CHECK JACKET NIÑA','Este pantalón clásico de pernera recta está confeccionado en mezcla de viscosa elástica con un elegante corte slim',689.9,15);
INSERT INTO products (name, description, price, category_id) VALUES ('FALDA MONOTYPE LABEL SKIRT NIÑA','Este pantalón, confeccionado en mezcla de viscosa elástica, presenta un corte slim y una favorecedora pernera recta',689.9,15);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALON  BRANDED RIB TAPE LEGGING NIÑA','Este pantalón de corte amplio, que luce un diseño recto clásico, es perfecto para combinar con tus conjuntos de noche',779.9,15);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALON  NOVA LEGGING NIÑA','Este pantalón de corte amplio, que luce un diseño recto clásico, es perfecto para combinar con tus conjuntos de noche',779.9,15);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA MONOTYPE TEE L /S NIÑA','Este jersey de cuello redondo y hombros caídos está confeccionada en un tejido texturizado de puro algodón y presenta un corte amplio',689.9,12);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA ESSENTIAL RIB TOP L /S NIÑA','Este vestido de punto trenzado luce un parche texturizado en el pecho, así como una capucha ajustable',659.9,22);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA NOVA SCRIPT TEE L /S NIÑA','Este vestido de punto trenzado luce un parche texturizado en el pecho, así como una capucha ajustable',659.9,22);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA ESSENTIAL DOWN JACKET NIÑO','Este producto contiene fibras de viscosa de LENZING™ ECOVERO™ procedentes de recursos madereros renovables y gestionados de forma sostenible',759.9,11);
INSERT INTO products (name, description, price, category_id) VALUES ('POLO ESSENTIAL POLO L /S NIÑO','Esta prenda brinda un toque elegante a tus looks casuales, este vestido es muy versátil ya que combina perfectamente con unas zapatillas o unas sandalias, además su tejido de algodón lo hace una opción cómoda para el día a día',699.9,11);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA AI METALLIC TEE L /S NIÑO','Esta prenda brinda un toque elegante a tus looks casuales, este vestido es muy versátil ya que combina perfectamente con unas zapatillas o unas sandalias, además su tejido de algodón lo hace una opción cómoda para el día a día',699.9,11);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA NOVA GRAFFITI TEE L /S NIÑO','Este vestido de corte evasé presenta una cintura ajustada y un estampado integral de plumas que le aportan un estilo bohemio y muy femenino',729.9,11);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA ESSENTIAL TEE L /S NIÑO','Perfecta para protegerse del frío en invierno, esta chaqueta presenta una capucha con acabado en pelo sintético, puños de punto elástico y relleno de plumón',679.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('CAMISETA KNIT TURTLENECK','Perfecta para protegerse del frío en invierno, esta chaqueta presenta una capucha con acabado en pelo sintético, puños de punto elástico y relleno de plumón',679.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA NEW YORK CHECK PUFFER JACKET','Perfecta para protegerse del frío en invierno, esta chaqueta presenta una capucha con acabado en pelo sintético, puños de punto elástico y relleno de plumón',679.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('SWEATSHIRT  BOLD GLOBAL STRIPE HALF ZIP','La chaqueta New York acolchada ofrece lo mejor del diseño contemporáneo para esta temporada',659.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('SWEATER SPRING GRID ZIP MOCK','La chaqueta New York acolchada ofrece lo mejor del diseño contemporáneo para esta temporada',659.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS CORE NOVA SUEDE HYBRID SHO','La chaqueta New York acolchada ofrece lo mejor del diseño contemporáneo para esta temporada',659.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('TJM AOP SHERPA JACKET','La chaqueta New York acolchada ofrece lo mejor del diseño contemporáneo para esta temporada',659.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('AIDEN OVSZ JACKET DG7017','Esta cazadora de corte amplio con capucha, decorada con un diseño integral de cuadros escoceses, es una opción elegante para combatir los días más fríos',699.9,27);
INSERT INTO products (name, description, price, category_id) VALUES ('TJM ALASKA VEST','Una prenda versátil que sera la adición preferida de tu pequeña, esta falda confeccionada en algodón se realza con los distintivos detalles de Nova y su cintura de punto elástico que facilita su ajuste',249.9,26);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA HW DOWN DIAMOND BAFFLE JACKET','Elige los estilos más cómodos de la temporada, estos leggins se diferencian de los demás por llevar un estilo pierna ancha y una cinturilla elástica distintiva con el logo de manera discreta',249.9,28);
INSERT INTO products (name, description, price, category_id) VALUES ('FALDA DNM LONG MIDI SKIRT CTD BLK','Estos modernos leggings con diseño largo están confeccionados en un tejido de mezcla de algodón ligeramente elástico que aporta comodidad y flexibilidad',199.9,28);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN RELAXED STRAIGHT HW ZIA WRN','Estos modernos leggings con diseño largo están confeccionados en un tejido de mezcla de algodón ligeramente elástico que aporta comodidad y flexibilidad',199.9,28);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN LOOSE STRAIGHT RW FAY','Esta versátil camiseta de manga larga, confeccionada en puro algodón, luce un cuello redondo y un logo monotipo de Nova en el pecho',199.9,25);
INSERT INTO products (name, description, price, category_id) VALUES ('JEAN WIDE LEG HW JOEY','Esta versátil camiseta de manga larga, confeccionada en puro algodón, luce un cuello redondo y un logo monotipo de Nova en el pecho',199.9,25);
INSERT INTO products (name, description, price, category_id) VALUES ('PANTALÓN IM SCULPT U SKINNY HW PANT','Esta camiseta de punto elástico, ideal para fiestas de cumpleaños o fines de semana, destaca por el bajo y los puños fruncidos',169.9,25);
INSERT INTO products (name, description, price, category_id) VALUES ('VESTIDO  ARGYLE CLR BLOCK DRESS LS','Perfecta para realzar looks informales, esta camiseta de manga larga está confeccionada en punto de algodón y se completa con un detalle distintivo en fuente Script',199.9,25);
INSERT INTO products (name, description, price, category_id) VALUES ('SMILEY SEQUIN LS TEE NIÑA','Perfecta para realzar looks informales, esta camiseta de manga larga está confeccionada en punto de algodón y se completa con un detalle distintivo en fuente Script',199.9,25);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA TJM ESSENTIAL JACKET','Ideal para completar looks para el aire libre, esta chaqueta elegante presenta un relleno cálido y una capucha extraíble muy práctica',679.9,24);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN FEMININE RUBBERIRZED BOOT','Ideal para completar looks para el aire libre, esta chaqueta elegante presenta un relleno cálido y una capucha extraíble muy práctica',679.9,24);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN ESSENTIAL SUEDE CHELSEA BOOT','Ideal para completar looks para el aire libre, esta chaqueta elegante presenta un relleno cálido y una capucha extraíble muy práctica',679.9,24);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN ESSENTIAL LEATHER CHELSEA BOOT','Ideal para completar looks para el aire libre, esta chaqueta elegante presenta un relleno cálido y una capucha extraíble muy práctica',679.9,24);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATILLAS TH HI BASKET SNEAKER','Perfecto para ocasiones semiformales, este refinado polo de manga larga puede llevarse solo o debajo de otra prenda en los días más fríos',249.9,23);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATILLAS TH PREMIUM HI BASKET SNEAKER','Elige la suavidad de esta cálida camiseta manga larga para niños, esta prenda realizada en un tejido de puro algodón se destaca por el logo metalizado que lleva en el pecho',199.9,23);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN HD TJW HIGH HEEL CHELSEA','Esta camiseta de manga larga, perfecta para los días otoñales, luce un logo Smiley estilo grafiti inspirado en la estética skater',219.9,23);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN HD TJW CHUNKY CHELSEA MIX MATERIA','Esta camiseta de corte clásico presenta un diseño de manga larga con puño y se realza con un detalle de costura en forma de V bajo el cuello redondo',149.9,23);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN HD TJW HIGH HEEL LACE UP BOOT','',239.9,10);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS IM TEXTURE LEATHER TH DRIVER','',239.9,10);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS CORE RWB NOVA SUEDE SHOE','',239.9,10);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN CORE MIX SUEDE HYBRID BOOT','',239.9,10);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN PREMIUM TH LEATHER HYBRID BOOT','',1990.9,1);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN NOVA CHUNKY HYBRID NBK BOO','',839.9,3);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN NOVA CHUNKY HYBRID SUEDE C','',699.9,2);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN PREMIUM TH SUEDE HYBRID CHELSE','Estos refinados zapatos híbridos, confeccionados en ante de gran calidad, presentan una suela gruesa muy moderna',699.9,6);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN CORE NOVA SUEDE BOOT','',919.9,9);
INSERT INTO products (name, description, price, category_id) VALUES ('BOTIN CORE W MIX CORDURA HYBRID BOOT','',919.9,9);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS CORPOARTE NOVA LTH DRIVER','',919.9,9);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS NOVA CREPE SUEDE LOAFER','',1390.9,13);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS NOVA CHUNKY HYBRID NBK SHO','',659.9,16);
INSERT INTO products (name, description, price, category_id) VALUES ('ZAPATOS IM TEXTURE CORPORATE TH DRIVER','',699.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA CLASSIC FILLED LAYDOWN COLLAR','',669.9,14);
INSERT INTO products (name, description, price, category_id) VALUES ('CASACA TJM REVERSIBLE QUILTED JACKET','',699.9,14);
GO

